server:
  port: ${SERVICE_PORT:8080}
spring:
  main:
    banner-mode: off
  webflux:
    base-path: /api/v1/loans-documents
  application:
    name: "vd-loans-documents-msa"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
app:
  init:
    promoter-id: ${INIT_PROMOTER_ID:0010007540}

adapter:
  rest-consumer:
    timeout: ${REST_TIMEOUT:5000}
    apis:
      renex:
        audience: ${GCP_AUDIENCE:renovacion-dev}
        api-health-customer: ${API_HEALTH_CUSTOMER:http://localhost:3001/customers-api/puc-customers/actuator/health}
        api-customer-process: ${API_CUSTOMER_PROCESS:http://localhost:3001/customers-api/puc-customers/customer/process/{processId}}
        api-health-offer: ${API_HEALTH_OFFER:https://vd-dev.csbservicios.com/offers-api/puc-offers/actuator/health}
        api-active-offer: ${API_ACTIVE_OFFER:http://localhost:3001/offers-api/puc-offers/offers/active-offering?processId={processId}}
      promoter:
        auth-token: ${API_PROMOTER_AUTH_TOKEN}
        channel: ${API_GET_AGREEMENT_CHANNEL:ECSB}
        api-generate-document: ${API_GENERATE_DOCUMENT_ENDPOINT:https://documents.qa.masnominadigital.com/api/generate/csb}
        api-get-agreement: ${API_GET_AGREEMENT_ENDPOINT:https://it-api-gateway.qa.masnominadigital.com/convenios/getDetail}
      api-connect:
        client-id: ${API_CONNECT_CLIENT_ID}
        application-id: ${API_CONNECT_APPLICATION_ID:CSB-CTE-APP}
        api-get-cnca: ${API_GET_CNCA:https://apic.consubanco.com/csb/qa/opc-service/getCNCALetter}
        api-search-interlocutor: ${API_SEARCH_INTERLOCUTOR:https://apic.consubanco.com/csb/qa/common-crm-service/searchInterlocutor}

  gcs-storage:
    max-file-size-mb: ${GCS_MAX_FILE_SIZE_IN_MB:0.5}
    bucket-name: ${GCS_BUCKET_NAME:csb-venta-digital}
    sign-url-days: ${GCS_SIGN_URL_DAYS:1}
    files-path:
      payload-template: ${GCS_PAYLOAD_TEMPLATE_PATH:management/puc-loans-documents-msa/payload-template.ftl}
      agreements-config: ${GCS_AGREEMENT_CONFIG:management/puc-loans-documents-msa/agreements-config.json}
entry:
  api:
    open-api:
      title: ${spring.application.name}
      version: 1.0.0
      description: Resolves loan document capabilities.
    path-services:
      health: /healthz
      agreement: /agreement
      file: /file
helpers:
  caffeine:
    expire-after-write: ${CACHE_EXPIRE_TIME_MINUTES:60}
    max-size-elements: ${CACHE_MAX_SIZE_ELEMENTS:100}

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
        show-details: always
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    disable-swagger-default-url: true
    path: </swagger.html>