server:
  port: 8080
spring:
  main:
    banner-mode: off
  webflux:
    base-path: /api/v1/loans-documents
  application:
    name: "vd-loans-documents-msa"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
app:
  init:
    promoter-id: ${APP_INIT_PROMOTER_ID:0010007540}
    agreements: ${APP_INIT_AGREEMENTS:10000041,10001121,10000080,10001183,10000790,10001103}

adapter:
  rest-consumer:
    timeout: ${REST_TIMEOUT:5000}
    apis:
      renex:
        pre-application: ${API_PRE_APPLICATION:https://apic.consubanco.com/csb/qa/opc-service/getPreApplicationData}
        get-active-offer: ${API_GET_ACTIVE_OFFER:/offers/active-offering/{processId}}
      promoter:
        auth-token: ${API_PROMOTER_AUTH_TOKEN}
        channel: ${API_GET_AGREEMENT_CHANNEL:ECSB}
        api-generate-document: ${API_GENERATE_DOCUMENT_ENDPOINT:https://documents.qa.masnominadigital.com/api/generate/csb}
        api-get-agreement: ${API_GET_AGREEMENT_ENDPOINT:https://it-api-gateway.qa.masnominadigital.com/convenios/getDetail}
      api-connect:
        client-id: ${API_CONNECT_CLIENT_ID}
        application-id: ${API_CONNECT_APPLICATION_ID:CSB-CTE-APP}
        api-get-cnca: ${API_GET_CNCA:https://apic.consubanco.com/csb/qa/opc-service/getCNCALetter}
        api-search-interlocutor: ${API_SEARCH_INTERLOCUTOR:https://apic.consubanco.com/csb/qa/common-crm-service/searchInterlocutor}

  gcs-storage:
    project-id: ${GCS_PROJECT_ID:csb-dev-venta-digital}
    bucket-name: ${GCS_BUCKET_NAME:csb-venta-digital}
    public-url: ${GCS_PUBLIC_URL:https://storage.googleapis.com/%s/%s}
    sign-url-days: ${GCS_SIGN_URL_DAYS:1}
    files-path:
      payload-template: ${GCS_PAYLOAD_TEMPLATE_PATH:management/puc-loans-documents-msa/payload-template.ftl}
entry:
  api:
    open-api:
      title: ${spring.application.name}
      version: 1.0.0
      description: Resolves loan document capabilities.
    path-services:
      agreement: /agreement
      file: /file
helpers:
  caffeine:
    expire-after-write: ${CACHE_EXPIRE_TIME_MINUTES:30}
    max-size-elements: ${CACHE_MAX_SIZE_ELEMENTS:100}

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
        show-details: always
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger.html