server:
  port: ${SERVICE_PORT:8080}
spring:
  main:
    banner-mode: off
  webflux:
    base-path: /api/v1/loans-documents
  application:
    name: "vd-loans-documents-msa"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  flyway:
    enabled: true
    baseline-version: 1
    locations: "classpath:db/migration"
    sql-migration-prefix: "V"
    sql-migration-suffixes: ".sql"
    baseline-on-migrate: true

adapter:
  rest-consumer:
    timeout: ${REST_TIMEOUT:30000}
    memory: ${REST_MAX_MEMORY_SIZE_MB:20}
    apis:
      renex:
        audience: ${GCP_AUDIENCE:renovacion-dev}
        api-health-customer: ${API_HEALTH_CUSTOMER:http://localhost:3001/customers-api/actuator/health}
        api-customer-process: ${API_CUSTOMER_PROCESS:http://localhost:3001/customers-api/customer/all-info/{processId}}
        api-customer-biometric-validation: ${API_CUSTOMER_BIOMETRIC_VALIDATION:http://localhost:3001/customers-api/biometric-validation/biometric-task/{processId}}
        api-health-offer: ${API_HEALTH_OFFER:http://localhost:3001/offers-api/actuator/health}
        api-active-offer: ${API_ACTIVE_OFFER:http://localhost:3001/offers-api/offers/active-offering?processId={processId}}
        api-validate-otp: ${API_VALIDATE_OTP:http://localhost:3001/authorization-api/otp/validate}
        api-accept-offer: ${API_ACCEPT_OFFER:http://localhost:3001/offers-api/offers/accept/{processId}}
      promoter:
        auth-token: ${API_PROMOTER_AUTH_TOKEN}
        channel: ${API_GET_AGREEMENT_CHANNEL:RENEX}
        api-generate-document: ${API_GENERATE_DOCUMENT_ENDPOINT:https://documents.qa.masnominadigital.com/api/generate/csb}
        api-generate-document-mn: ${API_GENERATE_DOCUMENT_ENDPOINT_MN:https://documents.qa.masnominadigital.com/api/generate}
        api-get-agreement: ${API_GET_AGREEMENT_ENDPOINT:https://it-api-gateway.qa.masnominadigital.com/convenios/getDetail}
      api-connect:
        valid-days-cnca: ${VALID_DAYS_CNCA:5}
        client-id: ${API_CONNECT_CLIENT_ID}
        application-id: ${API_CONNECT_APPLICATION_ID:CSB-RENEX}
        api-get-cnca: ${API_GET_CNCA:https://apic.consubanco.com/csb/qa/puc-letter-generate-api/getLetterCNCA}
        api-search-interlocutor: ${API_SEARCH_INTERLOCUTOR:https://apic.consubanco.com/csb/qa/common-crm-service/searchInterlocutor}
        api-send-generic-email: ${API_SEND_GENERIC_EMAIL:http://localhost:3001/ebanking-notification-service/sendGenericMail}
        api-branches-promoter: ${API_BRANCHES_BY_PROMOTER:https://apic.consubanco.com/csb/qa/opp-catalog-service/getBranchesByPromotor}
        api-docs-previous: ${API_DOCS_PREVIOUS:https://apic.consubanco.com/csb/qa/opp-service/findDocsPreviusApplication}
        api-create-application: ${API_CREATE_APPLICATION:http://localhost:3001/opp-service/createApplication}
      nom151:
        valid-time-min: ${VALID_TIME_IN_MINUTES_NOM151:30}
        endpoint: ${API_ENDPOINT_NOM151:https://wstestautosign.doc2sign.com/Doc2SignLite.svc}
        credentials:
          csb:
            user: ${API_USER_NOM151_CSB:d3aae0ff-d45d-455a-9929-014b5dd8b665}
            password: ${API_PASSWORD_NOM151_CSB:92850e29-6f0a-4b58-b3d5-54a82717e581}
          mas-nomina:
            user: ${API_USER_NOM151_MN:9fee015d-782c-40cf-81a8-49468f591d89}
            password: ${API_PASSWORD_NOM151_MN:0ecedfa4-0200-4601-9fc8-b10fbe6859f6}
        actions:
          load-document: ${ACTION_LOAD_DOCUMENT_NOM151:http://tempuri.org/IDoc2SignLite/Load}
          get-document-signed: ${ACTION_GET_DOCUMENT_SIGNED_NOM151:http://tempuri.org/IDoc2SignLite/GETDocFirmado}
          get-nom151: ${ACTION_GET_NOM151:http://tempuri.org/IDoc2SignLite/GETNOM}
        retry-strategy:
          max-retries: ${MAX_RETRIES_NOM151:10}
          retry-delay: ${RETRY_DELAY_IN_SECONDS_NOM151:1}

      ocr:
        days-range-for-pay-stubs-validation: ${DAYS_RANGE_FOR_PAY_STUBS_VALIDATION_OCR:45}
        api-key: ${API_KEY_OCR:pending}
        initial-delay-time: ${INITIAL_DELAY_TIME_IN_SECONDS_OCR:5}
        max-retries: ${MAX_RETRIES_OCR:20}
        retry-delay: ${RETRY_DELAY_IN_SECONDS_OCR:2}
        max-retry-delay: ${MAX_RETRY_DELAY_IN_MINUTES_OCR:1}
        application-id: ${API_CONNECT_APPLICATION_ID:CSB-RENEX}
        api-notify-document: ${API_NOTIFY_DOCUMENT_OCR:https://docia-integration-msa-24yvwrh62q-uw.a.run.app/doc-ia/notify-files}
        api-get-data-document: ${API_GET_DATA_DOCUMENT_OCR:https://docia-integration-msa-24yvwrh62q-uw.a.run.app/doc-ia/get-metadata}

  gcs-storage:
    max-file-size-mb: ${GCS_MAX_FILE_SIZE_IN_MB:10}
    bucket-name: ${GCS_BUCKET_NAME:csb-venta-digital}
    sign-url-days: ${GCS_SIGN_URL_DAYS:1}
    files-path:
      payload-template: ${GCS_PAYLOAD_TEMPLATE_PATH:management/vd-loans-documents-msa/payload-template.ftl}
      agreements-config: ${GCS_AGREEMENT_CONFIG:management/vd-loans-documents-msa/agreements-config.json}
      create-application-template: ${GCS_CREATE_APPLICATION_TEMPLATE_PATH:management/vd-loans-documents-msa/create-application-template.ftl}
  postgresql-repository:
    connection:
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: ${DB_DATABASE}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      script: db/migration/V1.0__init_schema.sql
      connection-timeout: ${DB_CONNECTION_TIMEOUT_IN_SECONDS:10}
      statement-timeout: ${DB_STATEMENT_TIMEOUT_IN_SECONDS:10}
      pool:
        initial-size: ${DB_MIN_CONNECTIONS:2}
        max-size: ${DB_MAX_CONNECTIONS:20}
        max-idle-time: ${DB_MAX_IDLE_TIME_IN_MINUTES:30}
        max-create-connection-time: ${DB_MAX_CREATE_CONNECTION_TIME_IN_SECONDS:30}
        max-acquire-time: ${DB_MAX_ACQUIRE_TIME_IN_SECONDS:30}
        max-life-time: ${DB_MAX_LIFE_TIME_IN_HOURS:2}
entry:
  api:
    open-api:
      title: ${spring.application.name}
      version: 1.0.0
      description: Resolves loan document capabilities.
    path-services:
      health: /healthz
      agreement: /agreement
      file: /file
      loans: /loans
      management: /management
      ocr: /ocr
helpers:
  caffeine:
    expire-after-write: ${CACHE_EXPIRE_TIME_MINUTES:60}
    max-size-elements: ${CACHE_MAX_SIZE_ELEMENTS:100}

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
        show-details: always
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger.html

logging:
  level:
    org.springframework: ${ENABLE_SPRING_LOGS:OFF}