name: Build and Publish Coverage Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    # Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    # Build the project and generate the coverage report
    - name: Build and generate coverage report
      run: ./gradlew build

    # Archive the coverage report
    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-coverage-report
        path: build/reports
        retention-days: 7
