name: Release Approval Process
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'The environment to deploy for'
        default: 'dev'
        required: true
        type: choice
        options:
          - 'dev'
          - 'qa'
          - 'prod'
jobs:
  workflow:
    uses: InnovacionTecnologicaCSP/devsecops-actions/.github/workflows/release.yml@main
    with:
      env: ${{ inputs.env }}
    secrets: inherit
